config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :bands


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64(16)
    token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?, :current_user

  def current_user
    #is there a session token???
    #set session token to @current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    #is a current_user ???
    !!current_user
  end

  def log_in_user!(user)
    #log in the user! and give their cookie a new session token
    session[:session_token] = user.reset_session_token!
  end

  def require_user!
    #if there isn't a user, redirect them
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to bands_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end





  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    #create a session if they logged in correctly
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    #session in line 23 is the cookie on the user's computer
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render json: @user.errors.full_messages
      # render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h1>Napster</h1>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <% if logged_in? %>
    <form action="<%= session_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Sign Out Sir">
    </form>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2 >Sign-up</h2>

<form action="<%= users_url %>" method="post">
  <!-- for views where a user submits information
  prevents CSRF attacks
  add to all view forms -->
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label >Email
    <input type="text" name="user[email]">
  </label>
</p>

<p>
  <label for="new-user-password">Password</label>
  <input id="new-user-password" type="password" name="user[password]">
</p>

  <input type="submit">

</form>

app/views/users/show.html.erb
<h1> ello sir </h1>

<p>
  your email: <%= current_user.email %>

</p>